### ISSUE TITLE
ExcelFile on Windows not closing appropriately

### ISSUE THREAD

**Issue by Mikuana** [Mikuana/rumydata#58]
Tests on Windows fail because the ExcelFile class that are opens files do not get appropriately closed before the test ends, which results in a exception. This appears to be related to the `read_only` property. An [issue](https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1450) has been opened on the `openpyxl` repo, and a related [PR](https://foss.heptapod.net/openpyxl/openpyxl/-/merge_requests/388) exists but has not yet been merged.

**Comment by Mikuana** [comment]
@snotpus This issue is caused by an external dependency in a project, which has an imminent fix coming. Will wait for that to be addressed, and will just ignore windows tests until then.

**Comment by Mikuana** [comment]
Once issue is resolved, add `openpyxl` version with fix to the package dependencies, and add Windows OS to GitHub test actions.

```
# python_versions_test.yml

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
        os: [ubuntu-latest, windows-latest, macos-latest]
```
